//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class JobPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPost()
        {
            this.SavedJobs = new HashSet<SavedJob>();
            this.Proposals = new HashSet<Proposal>();
        }

        public int Id { get; set; }
        public int ClientId { get; set; }
        [Display(Name = "Job Type")]
        [Required(ErrorMessage = "Please choose Job Type"), MaxLength(30)]
        public string JobType { get; set; }
        [Display(Name = "Job Title")]
        [Required(ErrorMessage = "Please enter Job Type"), MaxLength(30)]
        public string JobTitle { get; set; }
        [Display(Name = "Job Budget")]
        public int JobBudget { get; set; }

        public string JobDate { get; set; }
        [Display(Name = "Job Des")]
        [Required(ErrorMessage = "Please enter Job Description"), MaxLength(500)]
        public string JobDes { get; set; }

        public int PropNum { get; set; }
        public double Rate { get; set; }
        public int Approved { get; set; }
        public int Taken { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedJob> SavedJobs { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposal> Proposals { get; set; }
    }
}
