//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int FreelancerId { get; set; }
        public int Approved { get; set; }
    
        public virtual JobPost JobPost { get; set; }
        public virtual User User { get; set; }
    }
}
