//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.JobPosts = new HashSet<JobPost>();
            this.Proposals = new HashSet<Proposal>();
            this.SavedJobs = new HashSet<SavedJob>();
        }

        public int Id { get; set; }

        [RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$", ErrorMessage = "Email is not valid.")]
        [Required(ErrorMessage = "Please enter Email"), MaxLength(50)]
        public string Email { get; set; }


        [Display(Name = "User Name")]
        [Required(ErrorMessage = "Please enter User Name"), MaxLength(40)]
        public string UserName { get; set; }

        [MinLength(8, ErrorMessage = "Password must be at least 8 length")]
        [Required(ErrorMessage = "Please enter Password"), MaxLength(50)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please enter First Name"), MaxLength(40)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter Last Name"), MaxLength(40)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [RegularExpression(@"\+(9[976]\d|8[987530]\d|6[987]\d|5[90]\d|42\d|3[875]\d|2[98654321]\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1)\d{1,14}$", ErrorMessage = "Phone Number is not valid.")]
        [Required, MaxLength(30)]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        public string Photo { get; set; }
        [Display(Name = "User Type")]
        public string UserType { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPost> JobPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposal> Proposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedJob> SavedJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLogin> UserLogins { get; set; }
    }

    public class UserLogin
    {


        [RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$", ErrorMessage = "Email is not valid.")]
        [Required(ErrorMessage = "Please enter Email"), MaxLength(50)]
        public string Email { get; set; }

        [MinLength(8, ErrorMessage = "Password must be at least 8 length")]
        [Required(ErrorMessage = "Please enter Password"), MaxLength(50)]
        public string Password { get; set; }





    }

}
